SELECT  DISTINCT(MARKET) FROM DIM_CUSTOMER
WHERE CUSTOMER='ATLIQ EXCLUSIVE ' AND
REGION='APAC';
SELECT * FROM DIM_PRODUCT;
SELECT * FROM FACT_MANUFACTURING_COST;
--------------------------------------------------------------------------------------------------------------------

SELECT COUNT(DISTINCT(P.PRODUCT_CODE)) AS UNIQUE_PRODUCT ,
M.COST_YEAR FROM DIM_PRODUCT  P
JOIN FACT_MANUFACTURING_COST M ON
P.PRODUCT_CODE=M.PRODUCT_CODE
GROUP BY M.COST_YEAR;


WITH UNIQUE_PRODUCTS_IN_2020 AS (
  SELECT COUNT(DISTINCT PRODUCT_CODE) AS COUNT
  FROM FACT_SALES_MONTHLY
  WHERE FISCAL_YEAR = 2020
),
UNIQUE_PRODUCTS_IN_2021 AS (
  SELECT COUNT(DISTINCT PRODUCT_CODE) AS COUNT
  FROM FACT_SALES_MONTHLY
  WHERE FISCAL_YEAR = 2021
),
PERCENTAGE_DIFFERENCE AS (
  SELECT
    ((UNIQUE_PRODUCTS_IN_2021.COUNT - UNIQUE_PRODUCTS_IN_2020.COUNT) / UNIQUE_PRODUCTS_IN_2020.COUNT) * 100 AS PERCENTAGE_DIFFERENCE
  FROM UNIQUE_PRODUCTS_IN_2020, UNIQUE_PRODUCTS_IN_2021
)
SELECT
  UNIQUE_PRODUCTS_IN_2020.COUNT AS UNIQUE_PRODUCTS_2020,
  UNIQUE_PRODUCTS_IN_2021.COUNT AS UNIQUE_PRODUCTS_2021,
  PERCENTAGE_DIFFERENCE.PERCENTAGE_DIFFERENCE AS PERCENTAGE_CHANGE
FROM
  UNIQUE_PRODUCTS_IN_2020,
  UNIQUE_PRODUCTS_IN_2021,
  PERCENTAGE_DIFFERENCE;
 -------------------------------------------------------------------------------------------------------------- 
  
  SELECT COUNT(DISTINCT(PRODUCT))AS UNIQUE_PRODUCT_COUNTS ,
  SEGMENT FROM DIM_PRODUCT
  GROUP BY SEGMENT
  ORDER BY COUNT(DISTINCT(PRODUCT)) DESC;
  ---------------------------------------------------------------------------------------------------------------------
  
  
WITH 
F_2020 AS (
    SELECT SEGMENT, PRODUCT_CODE
    FROM DIM_PRODUCT
    JOIN FACT_SALES_MONTHLY USING (PRODUCT_CODE)
    WHERE FISCAL_YEAR = 2020
),
F_2021 AS (
    SELECT SEGMENT, PRODUCT_CODE
    FROM DIM_PRODUCT
    JOIN FACT_SALES_MONTHLY USING (PRODUCT_CODE)
    WHERE FISCAL_YEAR = 2021
),
F_2020_AGG AS (
    SELECT SEGMENT, COUNT(DISTINCT PRODUCT_CODE) AS PRODUCT_COUNT_2020
    FROM F_2020
    GROUP BY SEGMENT
),
F_2021_AGG AS (
    SELECT SEGMENT, COUNT(DISTINCT PRODUCT_CODE) AS PRODUCT_COUNT_2021
    FROM F_2021
    GROUP BY SEGMENT
)
SELECT 
    F_2020_AGG.SEGMENT, 
    F_2020_AGG.PRODUCT_COUNT_2020, 
    F_2021_AGG.PRODUCT_COUNT_2021, 
    (F_2021_AGG.PRODUCT_COUNT_2021 - F_2020_AGG.PRODUCT_COUNT_2020) AS DIFFERENCE
FROM F_2020_AGG
JOIN F_2021_AGG USING (SEGMENT)
ORDER BY DIFFERENCE DESC;
-------------------------------------------------------------------------------------------------------------------

(SELECT P.PRODUCT,P.PRODUCT_CODE, F.MANUFACTURING_COST MANUFACTURING_COST FROM DIM_PRODUCT P
JOIN FACT_MANUFACTURING_COST F ON F.PRODUCT_CODE=P.PRODUCT_CODE
ORDER BY F.MANUFACTURING_COST DESC
LIMIT 1)
UNION
(SELECT P.PRODUCT,P.PRODUCT_CODE, F.MANUFACTURING_COST AS MANUFACTURING_COST 
FROM DIM_PRODUCT P
JOIN FACT_MANUFACTURING_COST F ON F.PRODUCT_CODE=P.PRODUCT_CODE
ORDER BY F.MANUFACTURING_COST ASC
LIMIT 1);
------------------------------------------------------------------------------------------------------------------

SELECT C.CUSTOMER ,C.CUSTOMER_CODE,
ROUND(AVG(P.PRE_INVOICE_DISCOUNT_PCT),2) *100 AS AVERAGE_PRE_INVOICE_DISCOUNT 
 FROM DIM_CUSTOMER C 
 JOIN FACT_PRE_INVOICE_DEDUCTIONS P ON
 P.CUSTOMER_CODE=C.CUSTOMER_CODE
 WHERE C.MARKET='INDIA' AND P.FISCAL_YEAR=2021
 GROUP BY C.CUSTOMER,C.CUSTOMER_CODE
 ORDER BY AVERAGE_PRE_INVOICE_DISCOUNT DESC
 LIMIT 5;
 ----------------------------------------------------------------------------------------------------------------
 
 SELECT
 EXTRACT(MONTH FROM(FS.DATE)) AS MONTH,
 EXTRACT(YEAR FROM(FS.DATE)) AS YEAR,
 C.CUSTOMER , ROUND(SUM(FG.GROSS_PRICE* FS.SOLD_QUANTITY)) AS GROSS_AMOUNT
 FROM DIM_CUSTOMER C
 JOIN FACT_PRE_INVOICE_DEDUCTIONS F ON
 C.CUSTOMER_CODE=F.CUSTOMER_CODE
 JOIN FACT_SALES_MONTHLY FS ON
 FS.CUSTOMER_CODE=C.CUSTOMER_CODE 
 JOIN FACT_GROSS_PRICE FG ON
 FG.PRODUCT_CODE=FS.PRODUCT_CODE
 WHERE C.CUSTOMER='ATLIQ EXCLUSIVE'
 GROUP BY MONTH,YEAR 
 ORDER BY YEAR ASC,MONTH ASC;
 --------------------------------------------------------------------------------------------------------------------
 
SELECT
    EXTRACT(YEAR FROM FS.DATE) AS YEAR,
    EXTRACT(QUARTER FROM FS.DATE) AS QUARTER,
    SUM(FS.SOLD_QUANTITY)AS TOTAL_QUANTITY
FROM
    FACT_SALES_MONTHLY FS
WHERE EXTRACT(YEAR FROM (FS.DATE))=2020
GROUP BY
    EXTRACT(YEAR FROM FS.DATE),
    EXTRACT(QUARTER FROM FS.DATE)
ORDER BY
    TOTAL_QUANTITY DESC
LIMIT 1;
-------------------------------------------------------------------------------------------------------------------

SELECT
    C.CHANNEL,
    SUM(FG.GROSS_PRICE * FS.SOLD_QUANTITY) AS GROSS_SALES,
    (SUM(FG.GROSS_PRICE * FS.SOLD_QUANTITY) / (SELECT SUM(FG.GROSS_PRICE * FS.SOLD_QUANTITY)
    FROM FACT_SALES_MONTHLY FS
    JOIN FACT_GROSS_PRICE FG ON FG.PRODUCT_CODE = FS.PRODUCT_CODE
    WHERE FG.FISCAL_YEAR = 2021)) * 100 AS PERCENTAGE
FROM
    DIM_CUSTOMER C
JOIN
    FACT_SALES_MONTHLY FS ON C.CUSTOMER_CODE = FS.CUSTOMER_CODE
JOIN
    FACT_GROSS_PRICE FG ON FG.PRODUCT_CODE = FS.PRODUCT_CODE
WHERE
    FG.FISCAL_YEAR = 2021
GROUP BY
    C.CHANNEL
ORDER BY
    GROSS_SALES DESC;
------------------------------------------------------------------------------------------------------------------

SELECT
    T.PRODUCT,
    T.DIVISION,
    T.TOTAL_QUANTITY
FROM (
    SELECT
        P.PRODUCT AS PRODUCT,
        P.DIVISION AS DIVISION,
        SUM(FS.SOLD_QUANTITY) AS TOTAL_QUANTITY,
        ROW_NUMBER() OVER (PARTITION BY P.DIVISION ORDER BY SUM(FS.SOLD_QUANTITY) DESC) AS RN
    FROM
        DIM_PRODUCT P
    JOIN
        FACT_SALES_MONTHLY FS ON P.PRODUCT_CODE = FS.PRODUCT_CODE
    WHERE
        FS.FISCAL_YEAR = 2021
    GROUP BY
        P.DIVISION,
        P.PRODUCT
    ) T
WHERE
    T.RN <= 3
ORDER BY
    T.DIVISION,
    T.TOTAL_QUANTITY DESC;
    -------------------------------------------------------------------------------------------------------------